version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kanjimaster-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanji-backend
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/KanjiMaster?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: huyho2004
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DEEPL_API_KEY: 1ec67bc9-ed85-4793-a78e-2da054feb7e3:fx
    networks:
      - kanjimaster-network

volumes:
  redis_data:

networks:
  kanjimaster-network:
    driver: bridge
